# ansible n1 -m file -a "path/home/ec2-user/ all_dir state=directory"
---
- name: Install HTTP servers
  hosts: g1
  become: yes
  tasks:
    - name: Install HTTPD
      yum:
        name: httpd
        state: present
      when: ansible_distribution== "Amazon"

    - name: start httpd
      service:
        name: httpd
        state: started
        when: ansible_distribution== "Amazon"

    - name: enable httpd
      service:
        name: httpd
        enabled: yes
        when: ansible_distribution== "Amazon"

- name: Install and configure Apache2 on Ubuntu
  hosts: master
  become: yes
  tasks:
    - name: Install Apache2
      apt:
        name: apache2
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Start Apache2
      service:
        name: apache2
        state: started
      when: ansible_distribution == "Ubuntu"

    - name: Enable Apache2 to start on boot
      service:
        name: apache2
        enabled: yes
      when: ansible_distribution == "Ubuntu"


...